### ISSUE TITLE
typography-custom-font.css doesn't exist

### ISSUE THREAD

**Issue by vincentdchan** [SumiMakito/hexo-theme-typography#1]
`/css/typography-custom-font.css` is included in the html, but it can not be found in public resources folder, it cause a 404 error.

**Comment by pmtao** [comment]
@vincentdchan 删除这个链接就行了。
我提了一个 PR 对主题进行了一些增强，[参考这里](https://github.com/pmtao/hexo-theme-typography/wiki/Commit-description)。
可以按照[主题配置说明](https://github.com/pmtao/hexo-theme-typography/blob/master/README.md)试用一下。
