### ISSUE TITLE
图标问题，icon issue

### ISSUE THREAD

**Issue by lzm1988** [SumiMakito/hexo-theme-typography#3]
github 和 rss那几个图标太小了 
github's icon is to small

**Comment by SumiMakito** [comment]
Fixed in b1abd0f9017e1d1a6c772e870bf2245119937f14.
Thanks for your feedback.

Cheers

**Comment by SumiMakito** [comment]
Fixed in b1abd0f9017e1d1a6c772e870bf2245119937f14.
Thanks for your feedback.

Cheers
