### ISSUE TITLE
Scroll bar in main-container and figure

### ISSUE THREAD

**Issue by ddyjis** [SumiMakito/hexo-theme-typography#5]
The scroll bar is set to be always appear in `.main-container` and `figure` and looks incoherent with this elegant theme. Would it be better to change to `overlay`?

**Comment by SumiMakito** [comment]
Hello ddyjis,

Thanks for your suggestion!
But I found a section about `overflow: overlay` at [here](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow).
![2017-11-25 17 07 55](https://user-images.githubusercontent.com/5277268/33229110-4ae2ab0e-d203-11e7-977f-3ab5a66f3a16.png)
I don't know whether or not the `overflow: overlay` would bring some compatibility issues for some browsers. I'm still not quite sure.
BTW, I'd like to know what browser are you using. :)

**Comment by ddyjis** [comment]
I was using chrome 62 and there was always scroll bars shown even though the content is not overflow. It's strange that I cannot reproduce this issue now so I think it is fine.
