### ISSUE TITLE
Appearance of scrollbar in Firefox 52

### ISSUE THREAD

**Issue by asciian** [SumiMakito/hexo-theme-typography#6]
Hi, there.
Thank you for awesome theme. I use this theme on my blog.
I found the issue in Firefox v52.

the theme sets the `-moz-scrollbars-none` to `overflow-y` of `.main-container`.
It seems that the value is not available to `overflow-y`. it is `overflow`.
However , you can use `-moz-hidden-unscrollable` instead of it.

Cheers.

**Comment by SumiMakito** [comment]
Hello asciian,

Thanks for your feedback and I’ll take a look into the issue shortly. 

Cheers

**Comment by SumiMakito** [comment]
Hi asciian,

I found that the `overflow-x` and `overflow-y` properties of `.main-container` takes no effect after several tests. So I merged these properties into a single `overflow: hidden` and I think it would work well.

Related commit: ba295b4046bcb5d7abb423cad674134b1732987a
Any further comments are welcomed.
Thanks again for your feedback and have a nice day.
