### ISSUE TITLE
代码高亮与首页文字截断问题 Syntax highlighting & Read More function

### ISSUE THREAD

**Issue by iCyris** [SumiMakito/hexo-theme-typography#8]
1). 代码高亮问题：默认似乎没有代码高亮功能，是否支持高亮插件``` prism_plugin ```？如果需要修改可以去哪个位置修改？
2). 首页文字截断问题：无法通过``` <!--more--> ```来控制首页文字的展示长度。

1). The Syntax highlighting function doesn't work, and does it support the plugin ```prism```?
2). I can't use ``` <!--more--> ``` to control the content length shown on the homepage.

**Comment by imbadark** [comment]
能问下你是怎么解决这两个问题的么.... 而且代码前后经常会出现奇怪的空格.
很难受, tags页面也有些问题.

**Comment by iCyris** [comment]
> 能问下你是怎么解决这两个问题的么.... 而且代码前后经常会出现奇怪的空格.
> 很难受, tags页面也有些问题.

抱歉...我后来更换了主题所以关闭了这个 issue，没有解决这两个问题。
